const { Router } = require('express');
const { requireRole } = require('../session');
const now = () => new Date().toISOString();
module.exports = ({ db }) => {
  const router = Router();
  const letter = (d, ga) => `GATE PASS APPLICATION\n\nApplication ID: GA-${d.id || 'NEW'}\n\nFrom: ${ga.name}\nRole: GA\n\nStudent: ${d.studentName}\nClass: ${d.studentClass}\n\nDate: ${d.requestedDate || 'Not specified'}\nSubject: Gate Pass Request\n\nDear Warden,\n\nI respectfully submit this gate-pass request for ${d.studentName} (${d.studentClass}).${d.reason ? `\n\nReason: ${d.reason}` : ''}${d.destination ? `\nDestination: ${d.destination}` : ''}${d.requestedTime ? `\nRequested time: ${d.requestedTime}` : ''}${d.additionalNote ? `\nAdditional information: ${d.additionalNote}` : ''}\n\nKindly review and take the appropriate decision.\n\nRegards,\n${ga.name}\nGA`;
  router.get('/history', requireRole('GA'), async (req,res)=>{try { const { date, weekday, q, status }=req.query; let rows=await db.all(`SELECT g.*,u.name AS studentName,u.loginId AS studentLoginId,u.roomNumber,w.name AS wardenName,b.name AS blockedByName FROM gate_passes g JOIN users u ON u.id=g.studentId LEFT JOIN users w ON w.id=g.approvedBy LEFT JOIN users b ON b.id=g.blockedBy WHERE g.approvedAt IS NOT NULL ORDER BY g.approvedAt DESC`); rows=rows.filter(r=>{const d=new Date(r.approvedAt);return d.getDay()!==0 && (!date||r.approvedAt.slice(0,10)===date) && (!weekday||String(d.getDay())===weekday) && (!status||r.status===status) && (!q||`${r.id} ${r.studentName} ${r.studentLoginId}`.toLowerCase().includes(q.toLowerCase()));});res.json({passes:rows}); }catch(e){res.status(500).json({error:'Failed to fetch GA history.'});}});
  router.post('/applications', requireRole('GA'), async(req,res)=>{try { const d=req.body||{};if(!d.studentName?.trim()||!d.studentClass?.trim())return res.status(400).json({error:'Student name and class are required.'});const draft={...d,studentName:d.studentName.trim(),studentClass:d.studentClass.trim()};const generatedLetter=letter(draft,req.user);const r=await db.run('INSERT INTO ga_applications (gaId,gaName,studentName,studentClass,reason,destination,requestedDate,requestedTime,additionalNote,generatedLetter,status,createdAt) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',[req.user.id,req.user.name,draft.studentName,draft.studentClass,d.reason||null,d.destination||null,d.requestedDate||null,d.requestedTime||null,d.additionalNote||null,generatedLetter,'PENDING',now()]);const app=await db.get('SELECT * FROM ga_applications WHERE id=?',[r.lastInsertRowid]);app.generatedLetter=letter({...draft,id:app.id},req.user);await db.run('UPDATE ga_applications SET generatedLetter=? WHERE id=?',[app.generatedLetter,app.id]);res.status(201).json({application:app}); }catch(e){res.status(500).json({error:'Failed to send GA application.'});}});
  router.get('/applications', requireRole('GA'), async(req,res)=>{try{const rows=await db.all('SELECT a.*,u.name AS wardenName FROM ga_applications a LEFT JOIN users u ON u.id=COALESCE(a.approvedBy,a.rejectedBy) WHERE a.gaId=? ORDER BY a.id DESC',[req.user.id]);res.json({applications:rows});}catch(e){res.status(500).json({error:'Failed to fetch applications.'});}});
  router.get('/warden/applications', requireRole('WARDEN'), async(req,res)=>{try{const rows=await db.all('SELECT a.*,u.name AS wardenName FROM ga_applications a LEFT JOIN users u ON u.id=COALESCE(a.approvedBy,a.rejectedBy) ORDER BY a.id DESC');res.json({applications:rows});}catch(e){res.status(500).json({error:'Failed to fetch GA applications.'});}});
  router.post('/warden/applications/:id/:decision', requireRole('WARDEN'), async(req,res)=>{try{const a=await db.get('SELECT * FROM ga_applications WHERE id=?',[req.params.id]);if(!a)return res.status(404).json({error:'GA application not found.'});if(a.status!=='PENDING')return res.status(400).json({error:'This application has already been processed.'});const approved=req.params.decision==='approve';if(!approved&&req.params.decision!=='reject')return res.status(400).json({error:'Invalid decision.'});await db.run(approved?"UPDATE ga_applications SET status='APPROVED',approvedAt=?,approvedBy=? WHERE id=?":"UPDATE ga_applications SET status='REJECTED',rejectedAt=?,rejectedBy=?,rejectionReason=? WHERE id=?",approved?[now(),req.user.id,a.id]:[now(),req.user.id,req.body?.reason||'Not approved',a.id]);res.json({ok:true});}catch(e){res.status(500).json({error:'Failed to process GA application.'});}});
  return router;
};
