const { Router } = require('express');
const crypto = require('node:crypto');
const QRCode = require('qrcode');
const { requireRole } = require('../session');
const token = () => `GP-${crypto.randomBytes(4).toString('hex').toUpperCase()}`;
const now = () => new Date().toISOString();

module.exports = function gatePassRoutes({ db }) {
  const router = Router();
  async function event(gatePassId, action, previousStatus, newStatus, userId, metadata = null) { await db.run('INSERT INTO approval_history (gatePassId,action,previousStatus,newStatus,performedBy,performedAt,metadata) VALUES (?,?,?,?,?,?,?)', [gatePassId, action, previousStatus, newStatus, userId, now(), metadata ? JSON.stringify(metadata) : null]); }
  async function enrich(pass) {
    if (!pass) return null;
    const s = await db.get('SELECT name,loginId,roomNumber FROM users WHERE id=?', [pass.studentId]);
    const approver = pass.approvedBy ? await db.get('SELECT name FROM users WHERE id=?', [pass.approvedBy]) : null;
    const blocker = pass.blockedBy ? await db.get('SELECT name FROM users WHERE id=?', [pass.blockedBy]) : null;
    return { ...pass, studentName:s?.name || 'Unknown', studentLoginId:s?.loginId || '-', roomNumber:s?.roomNumber || '-', approvedByName:approver?.name || null, blockedByName:blocker?.name || null, isBlocked:Boolean(pass.blockedAt) };
  }
  router.post('/', requireRole('STUDENT'), async (req,res) => { try {
    const { reason, fromDateTime, toDateTime, destination='', description='', type='NORMAL' } = req.body || {}; const from = new Date(fromDateTime), to = new Date(toDateTime);
    if (!reason || !fromDateTime || !toDateTime || Number.isNaN(+from) || Number.isNaN(+to) || +from < Date.now() || +to <= +from) return res.status(400).json({error:'Enter a reason and valid future leave and return times.'});
    const r=await db.run('INSERT INTO gate_passes (studentId,reason,destination,description,type,fromDateTime,toDateTime,status) VALUES (?,?,?,?,?,?,?,?)',[req.user.id,reason,destination,description,type,fromDateTime,toDateTime,'PENDING']); await event(r.lastInsertRowid,'SUBMITTED',null,'PENDING',req.user.id);
    const wardens = await db.all("SELECT id FROM users WHERE role='WARDEN'");
    for (const warden of wardens) await db.run('INSERT INTO notifications (userId,title,body,type,referenceId,createdAt) VALUES (?,?,?,?,?,?)', [warden.id, 'New gate pass request', `${req.user.name} (${req.user.loginId}) submitted: ${reason}`, 'GATEPASS_SUBMITTED', r.lastInsertRowid, now()]);
    res.status(201).json({pass:await enrich(await db.get('SELECT * FROM gate_passes WHERE id=?',[r.lastInsertRowid]))});
  } catch(e){console.error(e);res.status(500).json({error:'Failed to create gate pass.'});} });
  router.get('/', requireRole('STUDENT','WARDEN','GA'), async (req,res)=>{ try { const rows=req.user.role==='STUDENT'?await db.all('SELECT * FROM gate_passes WHERE studentId=? ORDER BY id DESC',[req.user.id]):await db.all('SELECT * FROM gate_passes ORDER BY id DESC'); res.json({passes:await Promise.all(rows.map(enrich))}); }catch(e){res.status(500).json({error:'Failed to fetch gate passes.'});} });
  router.get('/history', requireRole('WARDEN'), async (req,res)=>{ try { const rows=await db.all(`SELECT h.*,u.name AS performedByName,g.studentId FROM approval_history h LEFT JOIN users u ON u.id=h.performedBy JOIN gate_passes g ON g.id=h.gatePassId ORDER BY h.id DESC`); res.json({history:rows}); }catch(e){res.status(500).json({error:'Failed to fetch approval history.'});} });
  router.post('/:id/approve', requireRole('WARDEN'), async (req,res)=>{ try { const p=await db.get('SELECT * FROM gate_passes WHERE id=?',[req.params.id]); if(!p)return res.status(404).json({error:'Gate pass not found.'}); if(p.status!=='PENDING')return res.status(400).json({error:'Only pending passes can be approved.'}); const time=now();await db.run("UPDATE gate_passes SET status='APPROVED',qrToken=?,approvedAt=?,approvedBy=?,approvalType='NORMAL' WHERE id=?",[token(),time,req.user.id,p.id]); await event(p.id,'APPROVED','PENDING','APPROVED',req.user.id);res.json({pass:await enrich(await db.get('SELECT * FROM gate_passes WHERE id=?',[p.id]))}); }catch(e){res.status(500).json({error:'Failed to approve gate pass.'});} });
  router.post('/:id/reject', requireRole('WARDEN'), async (req,res)=>{ try { const p=await db.get('SELECT * FROM gate_passes WHERE id=?',[req.params.id]); if(!p)return res.status(404).json({error:'Gate pass not found.'}); if(p.status!=='PENDING')return res.status(400).json({error:'Only pending passes can be rejected.'}); const time=now(), deadline=new Date(Date.now()+30*60000).toISOString(); await db.run("UPDATE gate_passes SET status='REJECTED',rejectedAt=?,rejectedBy=?,reapprovalDeadline=? WHERE id=?",[time,req.user.id,deadline,p.id]);await event(p.id,'REJECTED','PENDING','REJECTED',req.user.id);res.json({pass:await enrich(await db.get('SELECT * FROM gate_passes WHERE id=?',[p.id]))}); }catch(e){res.status(500).json({error:'Failed to reject gate pass.'});} });
  router.post('/:id/reapprove', requireRole('WARDEN'), async (req,res)=>{ try { const p=await db.get('SELECT * FROM gate_passes WHERE id=?',[req.params.id]); if(!p)return res.status(404).json({error:'Gate pass not found.'}); if(p.status!=='REJECTED'||!p.rejectedAt||!p.reapprovalDeadline||Date.now()>new Date(p.reapprovalDeadline).getTime())return res.status(400).json({error:'The 30-minute re-approval window has expired.'}); const time=now();await db.run("UPDATE gate_passes SET status='APPROVED',qrToken=?,approvedAt=?,approvedBy=?,approvalType='REAPPROVAL' WHERE id=?",[token(),time,req.user.id,p.id]);await event(p.id,'REAPPROVED','REJECTED','APPROVED',req.user.id);res.json({pass:await enrich(await db.get('SELECT * FROM gate_passes WHERE id=?',[p.id]))}); }catch(e){res.status(500).json({error:'Failed to re-approve gate pass.'});} });
  router.post('/:id/block', requireRole('GA'), async(req,res)=>{try{const p=await db.get('SELECT * FROM gate_passes WHERE id=?',[req.params.id]);const reason=(req.body?.reason||'Administrative restriction').trim();if(!p)return res.status(404).json({error:'Gate pass not found.'});if(p.status!=='APPROVED'||p.blockedAt)return res.status(400).json({error:'Only active approved passes can be blocked.'});const time=now();await db.run("UPDATE gate_passes SET status='BLOCKED',blockedAt=?,blockedBy=?,blockReason=? WHERE id=?",[time,req.user.id,reason,p.id]);await event(p.id,'BLOCKED','APPROVED','BLOCKED',req.user.id,{reason});res.json({pass:await enrich(await db.get('SELECT * FROM gate_passes WHERE id=?',[p.id]))});}catch(e){res.status(500).json({error:'Failed to block gate pass.'});}});
  router.get('/:id/qr', requireRole('STUDENT'), async(req,res)=>{try{const p=await db.get('SELECT * FROM gate_passes WHERE id=?',[req.params.id]);if(!p||p.studentId!==req.user.id)return res.status(404).json({error:'Gate pass not found.'});if(p.status!=='APPROVED'||p.blockedAt||!p.qrToken||new Date(p.toDateTime)<=new Date())return res.status(400).json({error:'This pass is not currently valid for QR use.'});const b=await QRCode.toBuffer(p.qrToken,{width:320,margin:2});res.type('png').send(b);}catch(e){res.status(500).json({error:'Could not load QR code.'});}});
  return router;
};
