import React,{useEffect,useRef,useState}from 'react'; import {api,formatDateTime}from '../api';
const tabs=['Pending','Emergency','Approved','Rejected','All Passes','Approval History','GA Applications'];
export default function WardenDashboard(){const[tab,setTab]=useState('Pending'),[passes,setPasses]=useState([]),[history,setHistory]=useState([]),[letters,setLetters]=useState([]),[busy,setBusy]=useState(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[notifications,setNotifications]=useState([]),[permission,setPermission]=useState(()=>typeof Notification==='undefined'?'unsupported':Notification.permission),seen=useRef(new Set());
 const load=async()=>{try{const [p,h,l]=await Promise.all([api('/api/gatepasses'),api('/api/gatepasses/history'),api('/api/ga/warden/applications')]);setPasses(p.passes||[]);setHistory(h.history||[]);setLetters(l.applications||[])}catch(e){setError(e.message)}};useEffect(()=>{load();const i=setInterval(load,10000);return()=>clearInterval(i)},[]);
 useEffect(()=>{let alive=true;const getNotifications=async()=>{try{const d=await api('/api/notifications');if(!alive)return;const items=d.notifications||[];setNotifications(items);const newItems=items.filter(n=>!n.readAt&&!seen.current.has(n.id));if(seen.current.size&&permission==='granted')newItems.forEach(n=>{const popup=new Notification(n.title,{body:n.body,tag:`gatepass-${n.id}`});popup.onclick=()=>{window.focus();setTab('Pending');api(`/api/notifications/${n.id}/read`,{method:'POST'}).catch(()=>{});popup.close();};});items.forEach(n=>seen.current.add(n.id));}catch(e){}};getNotifications();const i=setInterval(getNotifications,12000);return()=>{alive=false;clearInterval(i)};},[permission]);
 const enableNotifications=async()=>{if(typeof Notification==='undefined'){setError('Desktop notifications are not supported by this browser.');return;}const result=await Notification.requestPermission();setPermission(result);if(result!=='granted')setError('Desktop notifications were not allowed by the browser.');};
 const act=async(id,action,body={})=>{setBusy(`${action}${id}`);setError('');try{await api(`/api/gatepasses/${id}/${action}`,{method:'POST',body});await load()}catch(e){setError(e.message)}finally{setBusy(null)}};
 const letterAct=async(id,decision)=>{setBusy(`${decision}${id}`);try{await api(`/api/ga/warden/applications/${id}/${decision}`,{method:'POST',body:decision==='reject'?{reason:window.prompt('Rejection reason')||'Not approved'}:{}});await load()}catch(e){setError(e.message)}finally{setBusy(null)}};
 const filtered=passes.filter(p=>{if(tab==='Pending')return p.status==='PENDING';if(tab==='Emergency')return p.type==='EMERGENCY';if(tab==='Approved')return p.status==='APPROVED';if(tab==='Rejected')return p.status==='REJECTED';return true}).filter(p=>`${p.id} ${p.studentName}`.toLowerCase().includes(query.toLowerCase()));
 return <main className="container dashboard"><div className="dashboard-head"><div><p className="eyebrow">WARDEN CONSOLE</p><h1>{tab}</h1></div><div className="warden-tools"><span className="notification-count">{notifications.filter(n=>!n.readAt).length} new</span>{permission!=='granted'&&permission!=='unsupported'&&<button className="secondary notification-enable" onClick={enableNotifications}>Enable desktop alerts</button>}<input aria-label="Search passes" placeholder="Search student or pass ID" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><nav className="section-tabs">{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav>{error&&<p className="message error">{error}</p>}
 {tab==='Approval History'?<div className="card"><h2>Permanent approval audit trail</h2><div className="timeline">{history.map(h=><article key={h.id}><b>{h.action}</b><span>Pass #{h.gatePassId} · {h.performedByName||'System'} · {formatDateTime(h.performedAt)}</span>{h.metadata&&<small>{h.metadata}</small>}</article>)}</div>{!history.length&&<p className="empty-note">No events recorded yet.</p>}</div>:tab==='GA Applications'?<div className="pass-list">{letters.map(a=><article className="letter" key={a.id}><div className="pass-top"><b>GA APPLICATION #{a.id}</b><span className={`badge ${a.status}`}>{a.status}</span></div><pre>{a.generatedLetter}</pre>{a.status==='PENDING'&&<div className="actions"><button className="approve" disabled={busy} onClick={()=>letterAct(a.id,'approve')}>Approve</button><button className="reject" disabled={busy} onClick={()=>letterAct(a.id,'reject')}>Reject</button></div>}</article>)}{!letters.length&&<p className="empty-note">No GA applications.</p>}</div>:<><div className="pass-list">{filtered.map(p=><article className="pass-card" key={p.id}><div className="pass-top"><span className={`badge ${p.status}`}>{p.status}</span><small>#{p.id}</small></div><b>{p.studentName} · {p.studentLoginId}</b><p>{p.reason}</p><p className="times">Room {p.roomNumber}<br/>Leave {formatDateTime(p.fromDateTime)}<br/>Return {formatDateTime(p.toDateTime)}</p>{p.approvedAt&&<p className="muted">Approved {formatDateTime(p.approvedAt)} by {p.approvedByName}</p>}{p.status==='PENDING'&&<div className="actions"><button className="approve" disabled={busy} onClick={()=>act(p.id,'approve')}>Approve</button><button className="reject" disabled={busy} onClick={()=>act(p.id,'reject')}>Reject</button></div>}{p.status==='REJECTED'&&<button disabled={busy||Date.now()>new Date(p.reapprovalDeadline)} onClick={()=>act(p.id,'reapprove')}>{Date.now()>new Date(p.reapprovalDeadline)?'Re-approval window expired':'Approve again'}</button>}</article>)}</div>{!filtered.length&&<p className="empty-note">No passes in this view.</p>}</>}</main>}
